apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  ports:
   - port: 9042
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  labels:
    app: cassandra
spec:
  type: NodePort
  ports:
  - name: cql
    protocol: "TCP"
    port: 9042
    targetPort: 9042
    nodePort: 32042
  selector:
    app: cassandra

