kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv0
spec:
  capacity:
    storage: 200M
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/redis0
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv1
spec:
  capacity:
    storage: 200M
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/redis1
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv2
spec:
  capacity:
    storage: 200M
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/redis2
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv3
spec:
  capacity:
    storage: 200M
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/redis3
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M